version: "3"

services:
  socket:
    build: .
    command: npm start
    container_name: ChatSocket
    restart: unless-stopped
    volumes:
      - .:/ChatSocket
      - /ChatSocket/node_modules
    ports:
      - "2086:9000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge